export default actionTypes = {
    CREATE_NEW_PRAY_SUCCESS: "CREATE_NEW_PRAY_SUCCESS",
    UPDATE_PRAY_LIST_SUCCESS: "UPDATE_PRAY_LIST_SUCCESS",
    DELETE_ALL_PRAY_INPROGRESS_SUCCESS: "DELETE_ALL_PRAY_INPROGRESS_SUCCESS",
    EDIT_PRAY_SUCCESS: "EDIT_PRAY_SUCCESS",
    DELETE_PRAY_SUCCESS: "DELETE_PRAY_SUCCESS",
    UPDATE_STATUS_PRAY_SUCCESS: "UPDATE_STATUS_PRAY_SUCCESS",
    GET_NOTIFICATION_SUCCESS: "UPDATE_STATUS_PRAY_SUCCESS",

    GET_PROFILE_PEDDING :"GET_PROFILE_PEDDING",
    GET_PROFILE_SUCCESS :"GET_PROFILE_SUCCESS",
    GET_PROFILE_FAILED :"GET_PROFILE_FAILED",
}


