const ActionTypes = {
    CREATE_PRAYER_PENDING: "CREATE_PRAYER_PENDING",
    CREATE_PRAYER_SUCCESS: "CREATE_PRAYER_SUCCESS",
    CREATE_PRAYER_FAILED: "CREATE_PRAYER_FAILED",

    EDIT_PRAYER_PENDING: "EDIT_PRAYER_PENDING",
    EDIT_PRAYER_SUCCESS: "EDIT_PRAYER_SUCCESS",
    EDIT_PRAYER_FAILED: "EDIT_PRAYER_FAILED",

    GET_TEMPLATE_PRAYER_PENDING :"GET_TEMPLATE_PRAYER_PENDING",
    GET_TEMPLATE_PRAYER_SUCCESS :"GET_TEMPLATE_PRAYER_SUCCESS",
    GET_TEMPLATE_PRAYER_FAILED :"GET_TEMPLATE_PRAYER_FAILED",

}


export const actionTypes = ActionTypes;





