module.exports = {

    UPDATE_PRAYER_STATUS :"UPDATE_PRAYER_STATUS",
    SHOW_MODAL_QR_CODE :"SHOW_MODAL_QR_CODE",
    SHOW_SCANNER :"SHOW_SCANNER",
    SHOW_PRAYER_OPTION :"SHOW_PRAYER_OPTION",
    UPDATE_LIVE_STATUS :"UPDATE_LIVE_STATUS",
    FOLLOWING_PRAYER :"FOLLOWING_PRAYER",
    SHOW_CONFIRM_MODAL :"SHOW_CONFIRM_MODAL",
    NAVIGATE_SCREEN:"NAVIGATE_SCREEN",
};
