module.exports = {
    DELETE_ALL_PRAY_INPROGRESS :"DELETE_ALL_PRAY_INPROGRESS",
    DELETE_ALL_PRAY_COMPLETED :"DELETE_ALL_PRAY_COMPLETED",
    EDIT_PRAY :"EDIT_PRAY",
    DELETE_PRAY :"DELETE_PRAY",
    UPDATE_STATUS_PRAY :"UPDATE_STATUS_PRAY",
    DELETE_NOTIFICATION :"DELETE_NOTIFICATION",
    UPDATE_PRAY :"UPDATE_PRAY",
    GET_PRAY :"GET_PRAY",
    UPDATE_FOLLOWING :"UPDATE_FOLLOWING",
    UPDATE_NOTIFICATION :"UPDATE_NOTIFICATION",
    SHOW_MODAL_QR_CODE :"SHOW_MODAL_QR_CODE",
    UPDATE_LIVE_STATUS :"UPDATE_LIVE_STATUS",

};
