module.exports = {
    DRAWER_TOGGLE: "DrawerToggle",
    LOGIN_STACK: "LoginStack",
    DRAWER_NAV: "DrawerNav",
    SPLASH_SCREEN: 'SplashScreen',
    HOME_SCREEN: 'HomeScreen',
    LOGIN_SCREEN: 'LoginScreen',
    SIGNUP_SCREEN: 'SignupScreen',
    A_STACK: 'AStack',
    A_SCREEN: 'AScreen',
    A_SCREEN_DETAIL: 'AScreenDetail',
    B_SCREEN: 'BScreen',
    C_SCREEN: 'CScreen',
    LIST_COMMON: "ListCommon",
    PRAYING_INPROGESS: "PrayingInProgress",
    PRAY_FINISHED: "PrayFinished",
    CREATE_PRAYING: "CreatePraying",
    CREATE_ACCOUNT: "CreateAccount",
    PRAY_DETAIL: "PrayDetail",
    PRAY_FOR_OTHER :"PrayForOther",
    FORGOT_PASS: "ForgotPass",
    NOTIFICATIONS :"Notifications",
    NOTIFICATION_DETAIL :"NotificationDetail",
    PROFILE:"Profile",
    ABOUT :"About",
    INTRO :"Intro",

};
