# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNTemplate' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNTemplate

  target 'RNTemplate-tvOSTests' do
    inherit! :search_paths
    # Pods for testing

    pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

    pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  end

  target 'RNTemplateTests' do
    inherit! :search_paths
    # Pods for testing
  end


end

target 'RNTemplate-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNTemplate-tvOS


end
