# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNTemplate' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNTemplate

  target 'RNTemplate-tvOSTests' do
    inherit! :search_paths
    # Pods for testing

    pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

    pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  end
pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
   pod 'React', :path => '../node_modules/react-native', :subspecs => [
         'Core',
         'RCTActionSheet',
         'RCTAnimation',
         'RCTGeolocation',
         'RCTImage',
         'RCTLinkingIOS',
         'RCTNetwork',
         'RCTSettings',
         'RCTText',
         'RCTVibration',
         'RCTWebSocket',
         'ART'
         ]


  target 'RNTemplateTests' do
    inherit! :search_paths
    # Pods for testing
  end


end

target 'RNTemplate-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNTemplate-tvOS


end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == "React"
            target.remove_from_project
        end
    end
end
