export default actionTypes = {
    CREATE_NEW_PRAY_SUCCESS: "CREATE_NEW_PRAY_SUCCESS",
    UPDATE_PRAY_LIST_SUCCESS: "UPDATE_PRAY_LIST_SUCCESS",
    DELETE_ALL_PRAY_INPROGRESS_SUCCESS: "DELETE_ALL_PRAY_INPROGRESS_SUCCESS",

    DELETE_PRAYER_PENDING: "DELETE_PRAYER_PENDING",
    DELETE_PRAYER_SUCCESS: "DELETE_PRAYER_SUCCESS",
    DELETE_PRAYER_FAILED: "DELETE_PRAYER_FAILED",

    DELETE_NOTIFICATION_PENDING: "DELETE_NOTIFICATION_PENDING",
    DELETE_NOTIFICATION_SUCCESS: "DELETE_NOTIFICATION_SUCCESS",
    DELETE_NOTIFICATION_FAILED: "DELETE_NOTIFICATION_FAILED",

    UPDATE_STATUS_PRAYER_SUCCESS: "UPDATE_STATUS_PRAYER_SUCCESS",
    UPDATE_STATUS_PRAYER_PENDING: "UPDATE_STATUS_PRAYER_PENDING",
    UPDATE_STATUS_PRAYER_FAILED: "UPDATE_STATUS_PRAYER_FAILED",

    UPDATE_READ_STATUS_NOTIFICATION_PENDING: "UPDATE_READ_STATUS_NOTIFICATION_PENDING",
    UPDATE_READ_STATUS_NOTIFICATION_SUCCESS: "UPDATE_READ_STATUS_NOTIFICATION_SUCCESS",
    UPDATE_READ_STATUS_NOTIFICATION_FAILED: "UPDATE_READ_STATUS_NOTIFICATION_FAILED",

    GET_NOTIFICATION_PENDING: "GET_NOTIFICATION_PENDING",
    GET_NOTIFICATION_SUCCESS: "GET_NOTIFICATION_SUCCESS",
    GET_NOTIFICATION_FAILED: "GET_NOTIFICATION_FAILED",

    GET_PROFILE_PEDDING: "GET_PROFILE_PEDDING",
    GET_PROFILE_SUCCESS: "GET_PROFILE_SUCCESS",
    GET_PROFILE_FAILED: "GET_PROFILE_FAILED",

    GET_PROFILE_OTHER_PENDING: "GET_PROFILE_OTHER_PENDING",
    GET_PROFILE_OTHER_SUCCESS: "GET_PROFILE_OTHER_SUCCESS",
    GET_PROFILE_OTHER_FAILED: "GET_PROFILE_OTHER_FAILED",

    GET_PRAYER_PENDING: "GET_PRAYER_PENDING",
    GET_PRAYER_SUCCESS: "GET_PRAYER_SUCCESS",
    GET_PRAYER_FAILED: "GET_PRAYER_FAILED",

    FOLLOWING_PRAYER_PENDING: "FOLLOWING_PRAYER_PENDING",
    FOLLOWING_PRAYER_SUCCESS: "FOLLOWING_PRAYER_SUCCESS",
    FOLLOWING_PRAYER_FAILED: "FOLLOWING_PRAYER_FAILED",

    UPDATE_LIVE_STATUS_PENDING: "UPDATE_LIVE_STATUS_PENDING",
    UPDATE_LIVE_STATUS_SUCCESS: "UPDATE_LIVE_STATUS_SUCCESS",
    UPDATE_LIVE_STATUS_FAILED: "UPDATE_LIVE_STATUS_FAILED",

    LOGIN_PENDING: "LOGIN_PENDING",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILED: "LOGIN_FAILED",

    REGISTER_PENDING: "REGISTER_PENDING",
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    REGISTER_FAILED: "REGISTER_FAILED",

    SEND_FORGOT_PENDING: "SEND_FORGOT_PENDING",
    SEND_FORGOT_SUCCESS: "SEND_FORGOT_SUCCESS",
    SEND_FORGOT_FAILED: "SEND_FORGOT_FAILED",

    RESEND_VERIFY_EMAIL_PENDING: "RESEND_VERIFY_EMAIL_PENDING",
    RESEND_VERIFY_EMAIL_SUCCESS: "RESEND_VERIFY_EMAIL_SUCCESS",
    RESEND_VERIFY_EMAIL_FAILED: "RESEND_VERIFY_EMAIL_FAILED",

    LOGOUT_PENDING: "LOGOUT_PENDING",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILED: "LOGOUT_FAILED",

    GET_PRAYER_NEARBY_PENDING: "GET_PRAYER_NEARBY_PENDING",
    GET_PRAYER_NEARBY_SUCCESS: "GET_PRAYER_NEARBY_SUCCESS",
    GET_PRAYER_NEARBY_FAILED: "GET_PRAYER_NEARBY_FAILED",

    UPDATE_PROFILE_PENDING: "UPDATE_PROFILE_PENDING",
    UPDATE_PROFILE_SUCCESS: "UPDATE_PROFILE_SUCCESS",
    UPDATE_PROFILE_FAILED: "UPDATE_PROFILE_FAILED",

    UPDATE_AVATAR_PENDING :"UPDATE_AVATAR_PENDING",
    UPDATE_AVATAR_SUCCESS :"UPDATE_AVATAR_SUCCESS",
    UPDATE_AVATAR_FAILED :"UPDATE_AVATAR_FAILED",

}


