export default actionTypes = {
    CREATE_NEW_PRAY_SUCCESS: "CREATE_NEW_PRAY_SUCCESS",
    UPDATE_PRAY_LIST_SUCCESS: "UPDATE_PRAY_LIST_SUCCESS",
    DELETE_ALL_PRAY_INPROGRESS_SUCCESS: "DELETE_ALL_PRAY_INPROGRESS_SUCCESS",

    DELETE_PRAYER_PENDING: "DELETE_PRAYER_PENDING",
    DELETE_PRAYER_SUCCESS: "DELETE_PRAYER_SUCCESS",
    DELETE_PRAYER_FAILED: "DELETE_PRAYER_FAILED",

    UPDATE_STATUS_PRAYER_SUCCESS: "UPDATE_STATUS_PRAYER_SUCCESS",
    UPDATE_STATUS_PRAYER_PENDING: "UPDATE_STATUS_PRAYER_PENDING",
    UPDATE_STATUS_PRAYER_FAILED: "UPDATE_STATUS_PRAYER_FAILED",

    GET_NOTIFICATION_SUCCESS: "GET_NOTIFICATION_SUCCESS",

    GET_PROFILE_PEDDING :"GET_PROFILE_PEDDING",
    GET_PROFILE_SUCCESS :"GET_PROFILE_SUCCESS",
    GET_PROFILE_FAILED :"GET_PROFILE_FAILED",

    GET_PRAYER_PENDING :"GET_PRAYER_PENDING",
    GET_PRAYER_SUCCESS :"GET_PRAYER_SUCCESS",
    GET_PRAYER_FAILED :"GET_PRAYER_FAILED",

    FOLLOWING_PRAYER_PENDING:"FOLLOWING_PRAYER_PENDING",
    FOLLOWING_PRAYER_SUCCESS:"FOLLOWING_PRAYER_SUCCESS",
    FOLLOWING_PRAYER_FAILED:"FOLLOWING_PRAYER_FAILED",

    UPDATE_LIVE_STATUS_PENDING :"UPDATE_LIVE_STATUS_PENDING",
    UPDATE_LIVE_STATUS_SUCCESS :"UPDATE_LIVE_STATUS_SUCCESS",
    UPDATE_LIVE_STATUS_FAILED :"UPDATE_LIVE_STATUS_FAILED",

}


