
const ActionTypes ={
    GET_PRAYER_DETAIL_PENDING :"GET_PRAYER_DETAIL_PENDING",
    GET_PRAYER_DETAIL_SUCCESS :"GET_PRAYER_DETAIL_SUCCESS",
    GET_PRAYER_DETAIL_FAILED :"GET_PRAYER_DETAIL_FAILED",
}

export const actionTypes = ActionTypes;





