
const ActionTypes ={
    GET_TEMPLATE_DISTANCE_PRAYER_PENDING :"GET_TEMPLATE_DISTANCE_PRAYER_PENDING",
    GET_TEMPLATE_DISTANCE_PRAYER_SUCCESS :"GET_TEMPLATE_DISTANCE_PRAYER_SUCCESS",
    GET_TEMPLATE_DISTANCE_PRAYER_FAILED :"GET_TEMPLATE_DISTANCE_PRAYER_FAILED",
}


export const actionTypes = ActionTypes;





